# name: asyncio.CancelledErr 
exception asyncio.CancelledError