# name: c.PyErr_BadInternalC 
void PyErr_BadInternalCall()