# name: c.PyException_GetTra 
PyObject* PyException_GetTraceback(PyObjectÂ *ex)