# name: if (tb != NULL) {
   
if (tb != NULL) {
  PyException_SetTraceback(val, tb);
}