# name: c.PyException_GetCau 
PyObject* PyException_GetCause(PyObjectÂ *ex)